In [109]:
import numpy as np
from numpy.random import randint
import collections
from collections import Counter

In [110]:
N = 5
e_a = randint(0, 5, 100) #actual
e_b = randint(0, 5, 100)#predicted
O = np.zeros((N, N), dtype=np.float32)
w = np.zeros((N, N))

In [111]:
for i, j in zip(e_a, e_b):
    O[i, j] += 1

In [112]:
O

array([[ 4.,  3.,  9.,  2.,  2.],
       [ 4.,  3.,  4.,  1.,  5.],
       [ 5.,  8.,  6.,  6.,  5.],
       [ 6.,  4.,  6.,  1.,  6.],
       [ 0.,  2.,  1.,  4.,  3.]], dtype=float32)

In [113]:
O = O / np.sum(O)

In [114]:
for i in range(0, N):
    for j in range(0, N):
        w[i, j] = ((i-j)**2) / float(((N-1)**2))

In [115]:
w

array([[ 0.    ,  0.0625,  0.25  ,  0.5625,  1.    ],
       [ 0.0625,  0.    ,  0.0625,  0.25  ,  0.5625],
       [ 0.25  ,  0.0625,  0.    ,  0.0625,  0.25  ],
       [ 0.5625,  0.25  ,  0.0625,  0.    ,  0.0625],
       [ 1.    ,  0.5625,  0.25  ,  0.0625,  0.    ]])

In [120]:
e_a_hist = np.array(collections.OrderedDict(sorted(Counter(e_a).items())).values())
e_b_hist = np.array(collections.OrderedDict(sorted(Counter(e_b).items())).values())

#norm_hist_a = map(float, e_a_hist) / np.sum(e_a_hist)
#norm_hist_b = map(float, e_b_hist) / np.sum(e_b_hist)

In [121]:
E = np.outer(e_a_hist, e_b_hist)

In [123]:
E = E / np.sum(E)

In [124]:
np.sum(E), np.sum(O)

(0, 0.99999988)

In [100]:
np.multiply(w, E)

array([[ 0.        ,  0.00201875,  0.010925  ,  0.01816875,  0.0361    ],
       [ 0.0033    ,  0.        ,  0.0031625 ,  0.00935   ,  0.0235125 ],
       [ 0.0132    ,  0.0023375 ,  0.        ,  0.0023375 ,  0.01045   ],
       [ 0.0243    ,  0.00765   ,  0.0025875 ,  0.        ,  0.0021375 ],
       [ 0.0456    ,  0.01816875,  0.010925  ,  0.00201875,  0.        ]])

In [101]:
np.multiply(w, O)

array([[ 0.      ,  0.001875,  0.015   ,  0.0225  ,  0.02    ],
       [ 0.0025  ,  0.      ,  0.003125,  0.01    ,  0.028125],
       [ 0.0175  ,  0.003125,  0.      ,  0.001875,  0.0075  ],
       [ 0.016875,  0.005   ,  0.00125 ,  0.      ,  0.00375 ],
       [ 0.06    ,  0.016875,  0.015   ,  0.000625,  0.      ]])

In [107]:
k = 1 - np.sum(np.multiply(w, O)) / np.sum(np.multiply(w,E))

In [108]:
k

-0.017119823171863224